version: 2

models:
  - name: mart_example
    description: "Example mart model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
      - name: name
        description: "Example name field"
      - name: created_at
        description: "Timestamp when record was created"
      - name: name_upper
        description: "Uppercase version of name field"